### ISSUE TITLE
bug: unexpected message 'Are you sure server is running?'

### ISSUE THREAD

**Issue by Pavel2Bambuch** [appium/appium-inspector#1044]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello, I am facing some hard to speciffy problems with Appium inspector....
I installed and set up all needed credentials in properities of windows and everything seems working fine until I try to connect to Inspector.

When I do ping on my local host adress it is working, so when I tried command to see if port is aviable than somehow telnet was set to true and all seems fine, checked netstat - tuln(port was running and listening). 
Server for Appium is running and listening in console and in desktop app too. But somehow there is error from inspector which says are you sure if server is running... but it is. Another steps made was setting up firewall rules to be accessed and ok for ports 4720 and 4723 and I tried both of them. But still it somehow isn't working, why so?

I can get easilly logs from android virtual device from console, but still I need to use inspector for easier setting up of automation. :) 

I was reading all possible guides over the internet but still the answ. why it is reacting like server is unaviable for inspector wasn't find to fix my problem...

### Expected Behavior

It will connect without error which leads to are you sure if server is running.....

### Operating System

Windows

### Appium Inspector Version

2023.8.1.0

### Appium Version

2.0.1 in cmd and 1.22.3.0 in desktop

### Further Information

Was checking almostly all aviable guides on internet etc, but still wasn't able to find out the route.....
I am even willing to go via screen sharing to fix it....

**Comment by eglitise** [comment]
If you are using command-line Appium plus Appium Inspector, then the Appium Desktop app is entirely obsolete. I would suggest deleting it since it is insecure and not maintained.
If you are trying to connect to the same port that the command-line Appium is running on, then please check your connection details. Remember that Appium 2 requires `Remote Path` to be set to `/` by default, not `/wd/hub`.

**Comment by Pavel2Bambuch** [comment]
Adding some info
![Appium running in PowerShell](https://github.com/appium/appium-inspector/assets/134922549/1610bbd7-dc48-45d8-9cb1-90331c0e4059)
![Ping](https://github.com/appium/appium-inspector/assets/134922549/0bbce593-c562-47ae-8326-35756722e47a)
![NetSat](https://github.com/appium/appium-inspector/assets/134922549/92a12b80-d967-4e2c-8adf-9aeebf7fe5ae)
![Paths setting](https://github.com/appium/appium-inspector/assets/134922549/0e08b61b-eb55-476c-a9a9-b4a6a1a2c1b0)
![path 2](https://github.com/appium/appium-inspector/assets/134922549/0baad20f-cdd0-45f5-af56-c3445c13fb82)
![Path 3](https://github.com/appium/appium-inspector/assets/134922549/c56b6add-408e-4bc5-9006-971e1a8b1507)
![Inspector 1](https://github.com/appium/appium-inspector/assets/134922549/4f91b5fe-3439-45d2-be28-f96cd41cb9eb)
![Inspector 1 result](https://github.com/appium/appium-inspector/assets/134922549/ee5f7777-01ec-4e71-8758-aeb8316a6031)
![Inspector 2](https://github.com/appium/appium-inspector/assets/134922549/666d1c66-23c8-4acf-b2fb-29892d26d86c)
![Inspector 2 result](https://github.com/appium/appium-inspector/assets/134922549/d35d1500-5b18-408e-b94e-f179fdfec247)

**Comment by Pavel2Bambuch** [comment]
Even after trying different internet connection, it is not working.
After setting firewall to be aviable and ok for this port....
It still don't work.

**Comment by eglitise** [comment]
Thanks for all the screenshots. I think the problem is likely caused by the `SSL` checkbox in your Inspector screenshot - try unchecking that. I've personally never used it, but just now I tried to set it to checked for a set of working connection details, and I got the same error as you did.
Also note the Appium log output startup message - it provides you two IP addresses, the other being 127.0.0.1 (which is also the default value used by the Inspector). Therefore you can just set all the connection parameters to their default values, and I think it should work:
![image](https://github.com/appium/appium-inspector/assets/37242620/76b2d71b-6e42-49d9-995d-2f794a01cce0)

**Comment by Pavel2Bambuch** [comment]
OMG... I feel so dumb. :D Ye, it was SSL.... 👍
