### ISSUE TITLE
bug: IOS <When spying element using appium inspector ,instead of individual element getting as combined element .Development platform is React js

### ISSUE THREAD

**Issue by kapij89** [appium/appium-inspector#1624]
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

While trying to locate any element by Id, text or Accesibility_Id, the value for these attributes appears as a combined text as common XCUIElementTypeOther having all the element in single tag

### Expected Behavior

Expected to have
 individual element identified on screen. 
![Screenshot 2024-08-22 123944](https://github.com/user-attachments/assets/663f43bd-34ac-4ca9-9f9f-38508f4c89ae)
Instead coming as all element in single tag as XCUIElementTypeOther

### Operating System

Mac

### Appium Inspector Version

2024.3.4

**Comment by eglitise** [comment]
I do not know what is the inspector application shown in your screenshot, but it is not Appium Inspector. Since you are seeing the issue in other inspector apps, it is not an Appium Inspector-specific problem.
As for the issue itself, if your app is built in React Native, it is a known problem. Refer to these links:
* https://appium.github.io/appium-inspector/latest/troubleshooting/#cannot-see-full-source-tree-with-xcuitest-driver-react-native-app
* https://github.com/appium/appium/issues/14825

**Comment by eglitise** [comment]
Closing due to no response
