### ISSUE TITLE
Unable to Launch Application in Physical device.

### ISSUE THREAD

**Issue by sushkad** [appium/appium-inspector#171]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

Getting below alert while launching application in physical device using Appium Inspector.
Issue - Failed to create session. The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource.

## Environment

- I am running Appium Desktop version _<1.22.0>
- I am on Windows.
  

PFA Screenshot for your reference.
![image](https://user-images.githubusercontent.com/13194496/136560345-df9fab27-e78f-460c-bbae-5c9e99b0a3ee.png)

![image](https://user-images.githubusercontent.com/13194496/136560492-a8fc8e60-0782-4a19-9f10-a521edcd2f66.png)

**Comment by KazuCocoa** [comment]
Did you try https://github.com/appium/appium-inspector/issues/162#issuecomment-931436076 ?

https://github.com/appium/appium-desktop/releases/tag/v1.22.0
> The version still expects to have `/wd/hub` prefix as Remote Path

**Comment by EternalBlue0** [comment]
yes,but it still doesn't work






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "appium/appium-inspector"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月14日(星期四) 晚上11:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [appium/appium-inspector] Unable to Launch Application in Physical device. (#171)





 
@EternalBlue0 did you change your remote path to /wd/hub as suggested?
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by EternalBlue0** [comment]
Excuse me, what should I do? Because I just started this line, I'm not familiar with its configuration




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "appium/appium-inspector"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月14日(星期四) 晚上11:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [appium/appium-inspector] Unable to Launch Application in Physical device. (#171)





 
OK. Well one way or another this means your server is not accessible to the Inspector with the given information. Which host and port and path is your server running on? You can paste the first few lines of your Appium server log which contains this information.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jlipps** [comment]
For example, in the Requirements section, it says you need.

> A running Appium server accessible via the network by the Inspector (for example, an Appium server running on localhost, or one running on a cloud service).

That is why I asked, where is your Appium server running?

**Comment by sushkad** [comment]
Sir @jlipps and Sir @KazuCocoa Thank you so much for valuable support.
Issue gets resolved and connect the application properly.

**Solution - I put  /wd/hub in the Remote path.**
