### ISSUE TITLE
Unable to locate elements when using espresso driver

### ISSUE THREAD

**Issue by barnie-xero** [appium/appium-inspector#196]
## Appium or Appium Desktop?

You are reporting an issue at the Appium Desktop repository. Appium Desktop is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Desktop but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [ ] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem

When using Espresso driver, the xml wouldn't load completely. Works fine if using uiautomator2.
This makes it impossible to locate elements.

**_When using espresso driver_**
![image](https://user-images.githubusercontent.com/75957018/140665718-8de70fe4-f241-4f8a-ae44-172817fb3fe8.png)

**_When using uiautomator2_**
![image](https://user-images.githubusercontent.com/75957018/140665558-97d02a5b-b0f5-42e6-b6c8-5719f4d0347c.png)

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

**Comment by KazuCocoa** [comment]
Such differences can happen since UIA2 driver depends on https://developer.android.com/training/testing/ui-automator
while Espresso driver depends on https://developer.android.com/training/testing/espresso . If the root cause was the OS API internal, nothing can do on appium side.

It seems you used compose. Then, possibly Android's espresso framework could not find some elements.
Then, https://github.com/appium/appium/issues/15138#issuecomment-954702973 may help to interact with compose elements. (It is available via `appium@beta` for now.)
The feature is still in development, so please take a look at compose tests in https://github.com/appium/appium-espresso-driver/tree/master/test/functional/commands to catch up with their functionality. For example, https://github.com/appium/appium-espresso-driver/blob/master/test/functional/commands/jetpack-compose-source-e2e-specs.js#L32 allows you to get compose elements as Appium's page source.

Or as a workaround, you can get these elements via uiautomator in Espresso driver.
https://github.com/appium/appium-espresso-driver#mobile-uiautomator
https://github.com/appium/appium-espresso-driver#mobile-uiautomatorpagesource

**Comment by barnie-xero** [comment]
Thanks @KazuCocoa . As suggested I installed `appium@beta` and tried running a basic test. I am getting this error.
Anything obvious here? Thanks

![image](https://user-images.githubusercontent.com/75957018/140861934-2309459e-b974-47c9-a78a-ab25911903af.png)

**Comment by KazuCocoa** [comment]
Did the element exist in the page source in `compose` driver?

**Comment by barnie-xero** [comment]
Yeap, I double checked the xml

![image](https://user-images.githubusercontent.com/75957018/141019227-a78e9cd1-9fbd-4b31-881e-52e2b541ec6e.png)


![image](https://user-images.githubusercontent.com/75957018/141019206-d624c967-4ae4-471a-b229-1ed4bf9d32c8.png)

**Comment by KazuCocoa** [comment]
It seems you should use `-android viewtag` or `tag name` as selector https://github.com/appium/appium-espresso-driver/blob/41af90cf3a96018351ac689f43903b104693fbfc/test/functional/commands/jetpack-compose-e2e-specs.js#L36 or with XPath https://github.com/appium/appium-espresso-driver/blob/41af90cf3a96018351ac689f43903b104693fbfc/test/functional/commands/jetpack-compose-e2e-specs.js#L59 since it is an element attribute https://github.com/appium/appium-espresso-driver/blob/e2e4b288996250c354797ef3e7ac2fd71fbf7ba0/README.md#element-attributes

**Comment by KazuCocoa** [comment]
Close since this topic is currently `compose` stuff. (the topic is changed)

**Comment by barnie-xero** [comment]
Thanks @KazuCocoa . `-android viewtag` did worked for Espresso on `appium@beta`
