### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by genopapashvili** [appium/appium-inspector#241]
when I have opened appium inspector and in parallel I start a Junit test, this kills  the inspector's session

is there any way to stay both sessions?

I didn't find anything on google

how to change mod w3c to other 

I'm sorry  if I open an issue here by mistake

**Comment by KazuCocoa** [comment]
The behavior itself is expected.
You need to attach to an existing session instead of creating a new session by JUnit test. It depends on if the Java client code has such "attach" feature.

Appium-inspector has the attach to an existing session feature, so possibly you can try JUnit test first, then attach to the session via appium-inspector.
https://github.com/appium/appium-inspector#features

**Comment by KazuCocoa** [comment]
https://discuss.appium.io/ may also help to ask such questions

**Comment by genopapashvili** [comment]
@KazuCocoa  thank you for answer

in the eighteenth version it worked much better that it works now.

when I have started a session,   it shouldn't be killed by any other new session, no matter it is an Inspector or ordinary session

it would have  been better if I could give a life duration to both sessions from capabilities

**Comment by KazuCocoa** [comment]
ah, probably I misunderstood.

> stay both sessions?

Could you attach the full appium log?
I guess some parameters were not set properly https://appium.io/docs/en/advanced-concepts/parallel-tests/

**Comment by genopapashvili** [comment]
@KazuCocoa Hi
here are some files 
log: https://drive.google.com/file/d/1KTKLtxYAtg9-kalxbL9RyMQ3bT-pa_T8/view?usp=sharing
video record: https://drive.google.com/file/d/1y2Db77n1H8iHqmXBti82tMm6TQy8rJb2/view?usp=sharing

**Comment by KazuCocoa** [comment]
It seems when appium supported multiple sessions in an appium instance, the behavior changed to handle sessions.

Previously, appium assumed one session per appium instance. Then, the next new session creation should have failed.

But for now, an appium instance can handle multiple appium sessions. Then, it is not easy to detect actually a new session creation is for already running another session since `udid` is not a required parameter. Appium should consider some combinations, and they depend on each driver.


As your original question below,
> is there any way to stay both sessions?

you should provide capabilities properly https://appium.io/docs/en/advanced-concepts/parallel-tests/
Your current error is conflicted `systemPort`. You should set the value properly for each session to not get conflict.

**Comment by genopapashvili** [comment]
OK, thank you very much.
