### ISSUE TITLE
I am trying to run the appium inspector with the given information but I get the error and not opening the app in the emulator.

### ISSUE THREAD

**Issue by NikitaTurakhia** [appium/appium-inspector#439]
I want to open the app in the emulator from the appium inspector but I am getting below error. Does anyone know what may be the issue?

![image](https://user-images.githubusercontent.com/21182650/170520012-8704f88d-b690-4a27-8afe-e0d5e8ef1517.png)

**Comment by jlipps** [comment]
What did you learn by visiting the docs mentioned in the error message?

**Comment by ZY-future** [comment]
Maybe you choose the wrong params of  "Activity" ,or other params.I think you should  check carefully 
![image](https://user-images.githubusercontent.com/53501920/170886924-6c1a9974-0562-49c5-b2b5-bbde0b655cc7.png)

**Comment by eglitise** [comment]
Issue is likely caused by the provided combination of `appium:app` and `appium:appPackage`, without `appium:appActivity`. I would probably suggest using either _only_ `appium:app`, or `appium:appPackage` _and_ `appium:appActivity`.
See the [UiAutomator2 documentation on app startup issues](https://github.com/appium/appium-uiautomator2-driver/blob/master/docs/activity-startup.md) for more information.
For now, closing due to no response, and also this not being an issue with the Inspector.
