### ISSUE TITLE
Appium inspector - Exception when click on + button from Action window

### ISSUE THREAD

**Issue by DineeshK** [appium/appium-inspector#640]
## Appium inspector

Exception when click on + button from Actions window

## The problem

Unexpected error message is displaying when click on + button

## Environment

- I am running Appium Inspector version _<2022.9.1.>_.
- I am on (pick one):
    - [x] Mac
 ![Screenshot 2022-10-25 at 15 44 47](https://user-images.githubusercontent.com/47497385/197790310-e9bce081-0e66-4562-be51-22f2e0cb64f0.png)  
![Screenshot 2022-10-25 at 15 20 41](https://user-images.githubusercontent.com/47497385/197790294-7c2758d3-05a7-4587-b177-b5d0da96a986.png)

**Comment by jlipps** [comment]
OK ,thanks for the report

**Comment by jlipps** [comment]
Hi, can you send in the full appium server log associated with this session please?

**Comment by akashpatil8494** [comment]
Hello jlipps,
I am also facing similar issue.

After starting session on appium inspector I can see the app has launched and a screen shot of the app can be seen on inspector.

Now I want to add setSetting("driver", "compose") in order to access the compose elements of our app.

So, after navigating to Actions tab on inspector when I click on plus icon I am getting similar error shown in above screen shot.

Can you please provide solution for this issue?
This will be big help to inspect compose elements on appium inspector.

Appium version : 2.0
espresso@2.13.1 (automationName 'Espresso')

**Comment by jlipps** [comment]
@akashpatil8494 the Actions tab now refers to Touch Actions. sounds like you want something else, like the Commands tab

**Comment by jlipps** [comment]
also, might be easier to just set the setting via capabilities e.g. use the `appium:settings[<settingName>]` capability with the appropriate setting name.

**Comment by akashpatil8494** [comment]
> also, might be easier to just set the setting via capabilities e.g. use the `appium:settings[<settingName>]` capability with the appropriate setting name.

Hello @jlipps,

I tried adding appium:settings cap on appium inspector, but I can see in the appium logs this setting is ignored by appium.

**Please note that, with below caps I am able to launch the session on inspector but I can not access compose elements (Not able to inspect compose elements).**

Piece of Appium logs:
**[EspressoDriver@66c8] The following capabilities were provided, but are not recognized by Appium:
[EspressoDriver@66c8]   settings**

Caps:
{
  "platformName": "Android",
  "appium:deviceName": "emulator-5554",
  "appium:appPackage": "<package name of our app>",
  "appium:appActivity": "<activity name of our app>",
  "appium:automationName": "espresso",
  "appium:platformVersion": "10",
  "appium:settings": "compose",
  "appium:espressoBuildConfig": "{ \"additionalAndroidTestDependencies\": [\"androidx.lifecycle:lifecycle-common:2.3.0\",\"androidx.collection:collection-ktx:1.2.0\",\"org.jetbrains.kotlinx:kotlinx-coroutines-test:1.6.4\"]}"
}
 


**But with the automation I can do interaction with the compose elements because I have used driver.setSettings("driver", "compose") as cap in my code**

**Below is the piece of appium logs when execution done with automation**

Calling AppiumDriver.updateSettings() with args: [{"driver":"compose"},"3cb1ac78-7870-4c84-be62-f8c19a585b6b"]
[debug] [EspressoDriver@eda8 (3cb1ac78)] Matched '/appium/settings' to command name 'updateSettings'
[debug] [EspressoDriver@eda8 (3cb1ac78)] Proxying [POST /appium/settings] to [POST http://127.0.0.1:8300/session/9ee73068-9967-4d18-91ec-6dc480452d8c/appium/settings] with body: {"settings":{"driver":"compose"}}
[debug] [EspressoDriver@eda8 (3cb1ac78)] Got response with status 200: {"id":"59a08282-403e-4bdc-b9cc-ed8f78cd70b2","sessionId":"9ee73068-9967-4d18-91ec-6dc480452d8c","value":null}
[debug] [EspressoDriver@eda8 (3cb1ac78)] Responding to client with driver.updateSettings() result: null

**Comment by jlipps** [comment]
`appium:settings` is incorrect. it should be `appium:settings[driver]`

**Comment by akashpatil8494** [comment]
> `appium:settings` is incorrect. it should be `appium:settings[driver]`

Hi @jlipps,
Thanks a lot.  appium:settings[driver] did work for me.

Now I can see xml having lot of resource id but the value is in integer which surely I can not use in Automation.

Our Developers have provided [testTag](https://medium.com/bumble-tech/automating-android-jetpack-compose-using-appium-edb760fe79b9#:~:text=semantic%20property%20called-,testTag,-.%20This%20property%20can) for elements for our automation purpose.
**These test tags I can fetch with automation with getPageSouce(). But I can not see on appium inspector**.

**Sample xml after getting page source with automation: (We can see view-tag is available in xml)**
<ComposeNode class="ComposeNode" index="0" clickable="false" enabled="true" focused="false" scrollable="false" selected="false" checked="false" bounds="[0,63][1080,1794]" password="false" resource-id="1">  <ComposeNode class="ComposeNode" index="0" clickable="false" enabled="true" focused="false" scrollable="false" selected="false" checked="false" bounds="[0,63][1080,1794]" password="false" resource-id="2">    <EditableText class="EditableText" index="0" clickable="true" enabled="true" focused="false" scrollable="false" selected="false" checked="false" **view-tag="user_id_input"**  </ComposeNode></ComposeNode>

but in below screen shot we can see, there is no testTags or view-tag available 
<img width="1484" alt="Screenshot 2022-11-23 at 10 30 28 AM" src="https://user-images.githubusercontent.com/53179661/203524006-7d912b68-5a2e-4e6e-853a-141ba2b626c3.png">

Can you please help me to identify these testTags on appium inspector?
Or do our dev team needs to do something at app level so that testTags will be visible on inspector?

**Comment by jlipps** [comment]
When you look at the appium server log while using the inspector, do you see view-tag in the source returned?

**Comment by eglitise** [comment]
Closing due to no response
