### ISSUE TITLE
Interactions are not avaliable for this element

### ISSUE THREAD

**Issue by hcesaros** [appium/appium-inspector#832]
## Appium or Appium Inspector?

You are reporting an issue at the Appium Inspector repository. Appium Inspector is a wrapper around Appium. If you are having trouble running tests, it is much more likely that the problem you are encountering is not a problem with Appium Inspector but with Appium. For that reason we require you to have tried your testcase with Appium CLI before reporting issues. Check the checkbox below to confirm that you have proven your issue does _not_ reproduce on Appium itself:

- [X] I have verified that my issue does not occur with Appium and should be investigated as an Appium Inspector issue

## The problem

I have the problem below:
Interactions are not available for this element.

I'm using appium server version 1.22.3-4 and appium inspector version 2023.5.1
I'm not able to map elements on iOS, only Android.

## Environment

- I am running Appium Inspector version _<2023.5.1>_.
- I am on (pick one):
    - [X] Mac OS Ventura 13.3.1 - simulator iOS 16.2 or 16.4 - Xcode 14.3
    - [ ] Windows
    - [ ] Linux

**Comment by eglitise** [comment]
In my experience this is usually caused by the app itself, due to elements being updated and rebuilt without user input. This changes the element ID, which is why Appium Inspector cannot find it anymore.
I would suggest refreshing the source and then trying again (though this may not be useful if the element changes often). Since Appium 1 is no longer supported, please also try with Appium 2.
If this does not help, please provide Appium logs and Inspector screenshots for more context.

**Comment by hcesaros** [comment]
I managed to solve it, actually the problem is in Xcode 14.3 that for some reason the appium is not being compatible in the interaction of the elements.
I uninstalled version 14.3 and installed version 14.2 and it worked normally again.
