### ISSUE TITLE
Appium Inspector doesn't capture the Windows pop up window

### ISSUE THREAD

**Issue by WeiweiCai** [appium/appium-inspector#890]
## The problem

When using Appium + WinAppDriver to write the automation for configurating some Windows settings, we found the Windows pop up window **doesn't captured by Appium Inspector on Windows 11 machine.**
![image](https://github.com/appium/appium-inspector/assets/15260217/79fc96d0-d873-4f95-8f90-106e6778127c)

## Environment

Windows 11
Appium Inspector 2023.5.2
WinAppDriver 1.1.3.0

It can be captured on Windows 10 machine.
We tried find this item with its Name in code, but it cannot be found:
`SettingsSession.FindElementByName("Windows Media Player Legacy").Click();`

We want the code can run on both Windows 10 and Windows 11 to select one item in the pop up window. How can we capture it with Appium + WinAppDriver on Windows 11?

**Comment by eglitise** [comment]
This is most likely an issue with WinAppDriver and/or `appium-windows-driver`, rather than the Inspector. Try updating to the latest versions of Appium 2, `appium-windows-driver` and WinAppDriver, then try again.
If the problem persists, please create a new issue in [the main Appium repo](https://github.com/appium/appium/issues).

**Comment by WeiweiCai** [comment]
@eglitise  Thanks for your quick response.
But I'm confused on your suggestion. Could you explain more about your suggestion?
I only installed WinAppDriver and Appium Inspector on my machine. Both of them are latest version.
Why do I need to install addition Appium 2 and appium-windows-driver? Are they will affect Appium Inspector's capture result?
Thanks in advanced.

**Comment by eglitise** [comment]
If you are using Appium Inspector, then you must have an Appium server running in the background (otherwise I'm not sure how you are able to establish an Inspector session).
WinAppDriver itself has not been updated in a while, and has some long standing issues (e.g. lacking W3C compliance), some of which are remedied in `appium-windows-driver`. It is therefore possible that this additional layer will help resolve your issue.
