### ISSUE TITLE
Loss of app session when steering with Appium Inspector

### ISSUE THREAD

**Issue by MarkEcki3BIT** [appium/appium-inspector#92]
## The problem

Hello!

Clicking a specific menu entry within the app (“Sub App”), with Appium Inspector, leads to a session loss of the app (user get logged out).
Is this maybe a known issue? Do the attached logs point to any known bugs maybe?

Thank you for any input.

Logfiles:

[AppiumLog.txt](https://github.com/appium/appium/files/6981912/AppiumLog.txt)
[Logcat.txt](https://github.com/appium/appium/files/6981916/Logcat.txt)

## Environment

* Appium version (or git revision) that exhibits the issue: **1.20.2; 1.16.0**
* Last Appium version that did not exhibit the issue (if applicable): n/a
* Desktop OS/version used to run Appium: **Windows 10 x64 (10.0.19042)**
* Node.js version (unless using Appium.app|exe): n/a
* Npm or Yarn package manager: n/a
* Mobile platform/version under test: **Android 11**
* Real device or emulator/simulator: **Simulator Pixel 3a XL (API 30_x86) @ Android Studio 4.1.3**
* Appium CLI or Appium.app|exe: **Appium CLI**

**Comment by jlipps** [comment]
And just to double check: if you simply use the app manually outside of Appium entirely, this behaviour does not occur?

**Comment by MarkEcki3BIT** [comment]
Exactly. If you test manually the error does not occur.

**Comment by jlipps** [comment]
There is an exception in the Logcat, but I'm not sure what it measn. It appears you're running the UiAutomator2 driver? What happens if you create a UiAutomator2 test to perform the same steps? Does the issue happen then? I'm not seeing how Appium can be involved in this issue at all right now. And even if it is, I'm not seeing how it would be an issue with Appium Inspector, which is just a GUI client for Appium.
