### ISSUE TITLE
Unable to access inspector: "Inspector Move"

### ISSUE THREAD

**Issue by venkatprassu** [appium/appium-inspector#936]
> I am using Appium version 1.15.1 and Java JDK 17.

We do not support or maintain Appium 1 anymore. Consider using the UIA2 driver supplied with Appium 2.

Hi Appium team,

I hope this email finds you well. I wanted to inform you that I have successfully upgraded my Appium version from 1.15.1 to 1.22.3. The installation process went smoothly.

However, I am facing an issue where I am unable to start the inspector in Appium. Instead, I only see the "Inspector Move" option. Could you please guide me on how to access and start the inspector?

Your assistance in this matter would be greatly appreciated.

Thank you and regards,
Venkatesh

_Originally posted by @mykola-mokhnach in https://github.com/appium/appium/issues/18797#issuecomment-1602264014_

**Comment by eglitise** [comment]
First, to avoid confusion, let me establish the terminology behind related tools:
* Appium: the core tool providing mobile automation
* Appium Desktop: an inspector tool for use with Appium. It is provided as a desktop app, and comes bundled with Appium itself. This app is old, insecure, and unsupported. ***This is what you are using.***
* Appium Inspector: a newer, currently maintained version of Appium Desktop. Functionally identical, but does ***not*** come bundled with Appium anymore.

The solution to your problem is therefore:
1) Uninstall/remove Appium Desktop
2) Install Appium ***and*** Appium Inspector

Appium is distributed as a command-line tool, which you can install using `npm`. Please see more information [on the Appium repository](https://github.com/appium/appium). Note that it is recommended to use Appium 2, because Appium 1 is no longer supported.
Appium Inspector can be downloaded [from this repository](https://github.com/appium/appium-inspector/releases).

**Comment by eglitise** [comment]
Closing due to no response
